### ISSUE TITLE
Error: image library/spotify not found

### ISSUE THREAD

**Issue by ufa** [TomasTomecek/dockerfile-fedora-spotify#1]
Spotify in docker.io is missing. Do you know where can we download it?

sudo ./run.sh 
Unable to find image 'spotify:latest' locally
Trying to pull repository docker.io/library/spotify ... 
Pulling repository docker.io/library/spotify
Error: image library/spotify not found
docker: Error: image library/spotify not found.
See 'docker run --help'.

**Comment by TomasTomecek** [comment]
I've updated instructions how you can build your own image with spotify: https://github.com/TomasTomecek/dockerfile-fedora-spotify/commit/db4e23577eab014ca06c3db35c4bec7db808b099

Feel free to reopen if it doesn't work for you or anything is unclear.
