### ISSUE TITLE
bluetooth sound box with no sound

### ISSUE THREAD

**Issue by ufa** [TomasTomecek/dockerfile-fedora-spotify#2]
Container is working ok, but it cannot route bluetooth sound. 
Is there a way to change this?

**Comment by TomasTomecek** [comment]
spotify within container renders sound with alsa, not pulseaudio, this could be the first issue; second is that there are no libraries for bluetooth installed afaik. To be honest, I've never used bluetooth on linux so I have no idea how to install/configure/use it.

**Comment by ufa** [comment]
OK, I will try to make it work. Closing this

**Comment by TomasTomecek** [comment]
Feel free to send a pull request with a working solution. Thanks!
